### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by e-coders**
please remove the "button{display:inline-block}" if any problems occurs in index.html CSS.

### CODE REVIEW

**Comment by e-coders** [comment]
Thanks!! visit my site https://e-coders.github.io

**Comment by e-coders** [comment]
oh no!! something problem!! i'm again taking back. sorry!

**Comment by S-Vishwaja** [comment]
> oh no!! something problem!! i'm again taking back. sorry!

No problem

**Comment by e-coders** [comment]
Sorry!!

**Pull request merged**
